feat(idgenerator): Add `IIdGenerator` And Add `MasaApp`
masastack/MASA.Framework pull request #188
Opened 2022-08-09 05:40 UTC by zhenlei520

# Description

* Add `IIdGenerator` And Add `MasaApp`
* Remove the IsDefault property in Caller

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Extended the documentation

2022-08-09 06:28 UTC, doddgu requested changes

2022-08-09 06:28 UTC, doddgu commented on src/BuildingBlocks/Data/Masa.BuildingBlocks.Data/IdGenerator/DefaultIdGeneratorFactory.cs
> +    private readonly IServiceProvider _serviceProvider;
Move fileds upon the properties.

2022-08-09 06:28 UTC, doddgu commented on src/BuildingBlocks/Ddd/Domain/Masa.BuildingBlocks.Ddd.Domain/_Imports.cs
> +global using Masa.BuildingBlocks.Data.Contracts;
The using directive for 'Masa.BuildingBlocks.Data.Contracts' appeared previously in this namespace

2022-08-09 06:28 UTC, doddgu commented on src/BuildingBlocks/Service/Masa.BuildingBlocks.Service.Caller/CallerBase.cs
> +    ///
?

2022-08-09 06:28 UTC, doddgu commented on src/Contrib/Service/Masa.Contrib.Service.MinimalAPIs/BackgroundServices/InitializeMasaAppHostedService.cs
> +public class InitializeMasaAppHostedService : BackgroundService
Why it's a background service?

2022-08-09 08:25 UTC, zhenlei520 commented on src/Contrib/Service/Masa.Contrib.Service.MinimalAPIs/BackgroundServices/InitializeMasaAppHostedService.cs
> +public class InitializeMasaAppHostedService : BackgroundService
Processed

2022-08-09 09:39 UTC, doddgu requested changes

2022-08-09 09:39 UTC, doddgu commented on src/BuildingBlocks/Data/Masa.BuildingBlocks.Data/MasaApp.cs
> +public class MasaApp
Add a 'protected' constructor or the 'static' keyword to the class declaration.

2022-08-09 09:39 UTC, doddgu commented on src/BuildingBlocks/Data/Masa.BuildingBlocks.Data/IdGenerator/IdGeneratorFactory.cs
>  public class IdGeneratorFactory
Add a 'protected' constructor or the 'static' keyword to the class declaration.

2022-08-09 09:39 UTC, doddgu commented on src/Contrib/Configuration/Masa.Contrib.Configuration/Extensions/WebApplicationBuilderExtensions.cs
> +using Masa.BuildingBlocks.Data;
Move it to _Imports.

2022-08-09 09:55 UTC, doddgu approved these changes
LGTM

2022-08-10 07:09 UTC, doddgu approved these changes
LGTM

2022-08-10 07:24 UTC, merged