fix: Deal with code smells
masastack/MASA.Framework pull request #193
Opened 2022-08-11 08:21 UTC by zhenlei520

# Description

Deal with code smells

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Extended the documentation

2022-08-11 10:00 UTC, doddgu requested changes

2022-08-12 01:24 UTC, zhenlei520 commented on src/BuildingBlocks/Service/Masa.BuildingBlocks.Service.Caller/AbstractCaller.cs
> +    protected AbstractCaller(IServiceProvider serviceProvider)
Processed

2022-08-12 01:24 UTC, zhenlei520 commented on src/BuildingBlocks/Ddd/Domain/Masa.BuildingBlocks.Ddd.Domain/Entities/Entity.cs
Processed

2022-08-12 01:24 UTC, zhenlei520 commented on src/BuildingBlocks/Service/Masa.BuildingBlocks.Service.Caller/AbstractCaller.cs
> -    public virtual async Task<TResponse?> PatchAsync<TResponse>(
Processed

2022-08-12 03:33 UTC, doddgu requested changes

2022-08-12 03:33 UTC, doddgu commented on src/BuildingBlocks/Ddd/Domain/Masa.BuildingBlocks.Ddd.Domain/Entities/Entity.cs
No, you haven't fix it yet.

2022-08-16 02:07 UTC, merged