refactor: refactor dcc configuration
masastack/MASA.Framework pull request #215
Opened 2022-08-18 07:48 UTC by codding-y

# Description

refactor dcc configuration

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

2022-08-19 01:13 UTC, doddgu requested changes

2022-08-19 01:13 UTC, doddgu commented on src/Contrib/Configuration/ConfigurationApi/Masa.Contrib.Configuration.ConfigurationApi.Dcc/README.zh-CN.md
> +    "PublicId": "PublicId",
Why does it fell harder?

2022-08-19 02:44 UTC, doddgu approved these changes
LGTM

2022-08-23 06:51 UTC, zhenlei520 approved these changes
LGTM

2022-08-23 06:52 UTC, merged