feat(Caching) : Support cache key formatting
masastack/MASA.Framework pull request #285
Opened 2022-10-14 08:28 UTC by zhenlei520

# Description

feat(Caching) : Support cache key formatting

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Extended the documentation

2022-10-18 10:05 UTC, doddgu requested changes

2022-10-18 10:05 UTC, doddgu commented on src/Contrib/Caching/Distributed/Masa.Contrib.Caching.Distributed.StackExchangeRedis/README.zh-CN.md
> +    distributedCacheOptions.UseStackExchangeRedisCache();
How to use it with dcc?

2022-10-19 01:18 UTC, doddgu commented on src/Contrib/Caching/Distributed/Masa.Contrib.Caching.Distributed.StackExchangeRedis/Extensions/ServiceCollectionExtensions.cs
> +
Is resharper's rule blank or non-blank?

2022-10-19 05:02 UTC, zhenlei520 commented on src/Contrib/Caching/Distributed/Masa.Contrib.Caching.Distributed.StackExchangeRedis/README.zh-CN.md
> +#### 用法3 (结合Dcc使用)：
There is a slight difference between the first step and the second step

2022-10-19 05:07 UTC, doddgu commented on src/Contrib/Caching/Distributed/Masa.Contrib.Caching.Distributed.StackExchangeRedis/README.zh-CN.md
> +#### 用法3 (结合Dcc使用)：
I mean your document doesn't make it clear

2022-10-19 07:28 UTC, zhenlei520 commented on src/Contrib/Caching/Distributed/Masa.Contrib.Caching.Distributed.StackExchangeRedis/README.zh-CN.md
> +#### 用法3 (结合Dcc使用)：
Processed

2022-10-19 07:51 UTC, doddgu approved these changes
LGTM

2022-10-19 07:51 UTC, merged