Feature(openIdConnect) : optimize openIdConnect query client
masastack/MASA.Framework pull request #383
Opened 2022-12-22 01:43 UTC by 15168440402

# Description

_Please explain the changes you've made_

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

2022-12-22 02:09 UTC, zhenlei520 approved these changes
LGTM

2022-12-22 10:14 UTC, zhenlei520 requested changes

2022-12-22 10:14 UTC, zhenlei520 commented on src/Contrib/Authentication/OpenIdConnect/Tests/Masa.Contrib.Authentication.OpenIdConnect.EFCore.Tests/SyncCacheTest.cs
> +using Masa.BuildingBlocks.Authentication.OpenIdConnect.Domain.Entities;
use global using

2022-12-23 07:31 UTC, doddgu commented
[11.1% Coverage](https://sonarcloud.io/component_measures?id=masastack_MASA.Framework&pullRequest=383&metric=new_coverage&view=list)

2022-12-26 04:37 UTC, zhenlei520 approved these changes
LGTM @doddgu

2022-12-26 05:58 UTC, doddgu approved these changes
LGTM

2022-12-26 05:58 UTC, merged