feat(tsc): add custom metrics
masastack/MASA.Framework pull request #390
Opened 2023-01-04 01:06 UTC by Qinyouzeng

2023-01-04 03:40 UTC, doddgu requested changes

2023-01-04 03:40 UTC, doddgu commented on src/Contrib/StackSdks/Masa.Contrib.StackSdks.Tsc/Metrics/MasaServiceExtensions.cs
> +            .AddAspNetCoreInstrumentation()
format.

2023-01-04 03:40 UTC, doddgu commented on src/Contrib/StackSdks/Masa.Contrib.StackSdks.Tsc/Tracing/Handler/AspNetCoreInstrumentationHandler.cs
> +        return false;
Always false?

2023-01-04 03:40 UTC, doddgu commented on src/Contrib/StackSdks/Masa.Contrib.StackSdks.Tsc/Tracing/Handler/HttpClientInstrumentHandler.cs
> +        return false;
Always false?

2023-01-05 05:34 UTC, Qinyouzeng commented on src/Contrib/StackSdks/Masa.Contrib.StackSdks.Tsc/Tracing/Handler/AspNetCoreInstrumentationHandler.cs
> +        return false;
Remove,not use

2023-01-05 05:34 UTC, Qinyouzeng commented on src/Contrib/StackSdks/Masa.Contrib.StackSdks.Tsc/Tracing/Handler/HttpClientInstrumentHandler.cs
> +        return false;
Remove,not use

2023-01-05 08:51 UTC, doddgu approved these changes
LGTM

2023-01-05 08:51 UTC, merged