Refactor/caller
masastack/MASA.Framework pull request #391
Opened 2023-01-04 10:21 UTC by MayueCif

2023-01-04 10:24 UTC, zhenlei520 requested changes

2023-01-04 10:24 UTC, zhenlei520 commented on src/Contrib/StackSdks/Masa.Contrib.StackSdks.Mc/ServiceCollectionExtensions.cs
> +            throw new ArgumentNullException(nameof(mcServiceBaseAddress));
MasaArgumentException.ThrowIfNull(mcServiceBaseAddress)

2023-01-04 10:24 UTC, zhenlei520 commented on src/Contrib/StackSdks/Masa.Contrib.StackSdks.Mc/ServiceCollectionExtensions.cs
>          ArgumentNullException.ThrowIfNull(callerOptions, nameof(callerOptions));
MasaArgumentException.ThrowIfNull(callerOptions)

2023-01-04 11:16 UTC, zhenlei520 approved these changes
LGTM @doddgu

2023-01-05 03:29 UTC, doddgu requested changes

2023-01-05 03:31 UTC, MayueCif commented on src/Contrib/Service/Caller/Masa.Contrib.Service.Caller.HttpClient/CallerOptionsExtensions.cs
> +        bool isSupportUpdate = false)
change envirment udpate caller request address

2023-01-05 08:51 UTC, doddgu approved these changes
LGTM

2023-01-05 08:51 UTC, merged