fix(tsc-elasticsearch-scroll):update scroll search method
masastack/MASA.Framework pull request #397
Opened 2023-01-07 09:47 UTC by Qinyouzeng

2023-01-08 09:49 UTC, zhenlei520 requested changes

2023-01-08 09:49 UTC, zhenlei520 commented on src/Contrib/StackSdks/Masa.Contrib.StackSdks.Tsc.Elasticsearch/Extenistions/IElasticClientExtenstion.cs
> +            throw new UserFriendlyException($"elastic query error: status:{response.ServerError?.Status},message:{response.OriginalException?.Message ?? response.ServerError?.ToString()},DebugInforma
format code

2023-01-08 09:49 UTC, zhenlei520 commented on src/Contrib/StackSdks/Masa.Contrib.StackSdks.Tsc.Elasticsearch/Extenistions/IElasticClientExtenstion.cs
> +                    searchResponse = await client.SearchAsync<TResult>(s => searchDescriptorFunc(s.Index(indexName)).Scroll(scrollQuery.Scroll));
Use the ternary operator

2023-01-09 01:18 UTC, zhenlei520 requested changes

2023-01-09 01:18 UTC, zhenlei520 commented on src/Contrib/StackSdks/Masa.Contrib.StackSdks.Tsc.Elasticsearch/TraceService.cs
> +        return await _client.SearchTraceAsync(query);
It can be considered that await is not applicable and returns directly to Task<PaginatedListBase<TraceResponseDto>>

2023-01-09 01:42 UTC, zhenlei520 approved these changes
LGTM @doddgu

2023-01-09 02:38 UTC, doddgu approved these changes
LGTM

2023-01-09 02:39 UTC, merged