feat: masa stack config  support dcc
masastack/MASA.Framework pull request #456
Opened 2023-02-15 05:26 UTC by codding-y

2023-02-15 05:36 UTC, MayueCif commented on src/Contrib/StackSdks/Masa.Contrib.StackSdks.Config/MasaStackConfigExtensions.cs
> +        return GetServerDomain(masaStackConfig, HttpProtocol.HTTPS, MasaStackConstant.DCC, MasaStackConstant.SERVER);
？

2023-02-15 05:37 UTC, MayueCif commented on src/Contrib/StackSdks/Masa.Contrib.StackSdks.Config/MasaStackConfigOptions.cs
>  public class MasaStackConfigOptions
static

2023-02-15 05:40 UTC, MayueCif commented on src/Contrib/StackSdks/Masa.Contrib.StackSdks.Config/ServiceCollectionExtensions.cs
> +            services.TryAddScoped<IMasaStackConfig>(serviceProvider =>
single

2023-02-15 05:56 UTC, MayueCif approved these changes
@zhenlei520

2023-02-15 12:44 UTC, zhenlei520 requested changes

2023-02-15 12:44 UTC, zhenlei520 commented on src/Contrib/StackSdks/Masa.Contrib.StackSdks.Config/MasaStackConfigExtensions.cs
> +        return JsonSerializer.Deserialize<DccOptions>(stringBuilder.ToString()) ?? throw new JsonException();
Why not manually initialize DccOptions and assign values?

2023-02-15 12:44 UTC, zhenlei520 commented on src/Contrib/StackSdks/Masa.Contrib.StackSdks.Config/ServiceCollectionExtensions.cs
> +                });
After the remote Dcc configuration is changed, it is inappropriate to change the obtained configuration immediately. In the same request, the obtained configuration should always be the same, even if the configuration is modified before the request ends

2023-02-15 12:44 UTC, zhenlei520 commented on src/Contrib/StackSdks/Masa.Contrib.StackSdks.Config/ServiceCollectionExtensions.cs
> +                return new MasaStackConfig(new(), client);
Use a constructor with only one parameter of type IConfigurationApiClient

2023-02-15 12:44 UTC, zhenlei520 commented on src/Contrib/StackSdks/Tests/Masa.Contrib.StackSdks.Middleware.Tests/RequestMiddlewareTest.cs
> +using Masa.BuildingBlocks.StackSdks.Config;
use global using

2023-02-16 07:36 UTC, zhenlei520 approved these changes

2023-02-16 07:37 UTC, merged