feat: Add Background Job
masastack/MASA.Framework pull request #480
Opened 2023-03-03 11:27 UTC by zhenlei520

# Description

Add Background Job

2023-03-05 05:56 UTC, doddgu commented
3 Code Smells, and 55.6 Coverage.

2023-03-07 10:29 UTC, doddgu requested changes

2023-03-07 10:29 UTC, doddgu commented on src/Contrib/Extensions/Masa.Contrib.Extensions.BackgroundJobs/BackgroundJobOptions.cs
> +    /// default: 5s
default? Default?

2023-03-07 10:29 UTC, doddgu commented on src/Contrib/Extensions/Masa.Contrib.Extensions.BackgroundJobs/BackgroundJobOptions.cs
> +    /// Default is 10
default? Default?

2023-03-07 10:29 UTC, doddgu commented on src/Contrib/Extensions/Masa.Contrib.Extensions.BackgroundJobs/BackgroundJobOptions.cs
> +    public int FirstWaitDuration
s? ms? m?

2023-03-07 10:29 UTC, doddgu commented on src/Contrib/Extensions/Masa.Contrib.Extensions.BackgroundJobs/BackgroundJobOptions.cs
> +    public int WaitDuration
s? ms? m?

2023-03-07 10:29 UTC, doddgu commented on src/Contrib/Extensions/Masa.Contrib.Extensions.BackgroundJobs/BackgroundJobProcessor.cs
> +                var nextTryTime = NextTryTime(job);
Same as above except logger message?

2023-03-13 02:56 UTC, zhenlei520 commented on src/Contrib/Extensions/Masa.Contrib.Extensions.BackgroundJobs/BackgroundJobProcessor.cs
> +                var nextTryTime = NextTryTime(job);
Processed

2023-03-13 11:24 UTC, doddgu approved these changes
LGTM

2023-03-13 11:25 UTC, merged