feat: All modules support isolation
masastack/MASA.Framework pull request #506
Opened 2023-03-17 12:13 UTC by zhenlei520

# Description

All modules support isolation

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Extended the documentation

2023-03-23 10:41 UTC, doddgu requested changes

2023-03-23 10:41 UTC, doddgu commented on src/BuildingBlocks/Isolation/Masa.BuildingBlocks.Isolation/DefaultIsolationConfigProvider.cs
> +    private readonly List<ModuleConfigRelationInfo> _data;
Module?

2023-03-23 10:41 UTC, doddgu commented on src/BuildingBlocks/Service/Masa.BuildingBlocks.Service.Caller/AbstractCaller.cs
> +public abstract class AbstractCaller : ICallerDisposeManual
IFullCaller? IManualCaller?

2023-03-23 10:41 UTC, doddgu commented on src/Contrib/Storage/ObjectStorage/Masa.Contrib.Storage.ObjectStorage.Aliyun/Internal/AliyunStorageConfigureOptions.cs
> +    ///
?

2023-03-23 10:41 UTC, doddgu commented on temp/WebApplication1/ApplicationServices/RegisterUser/RegisterUserEvent.cs
> +﻿// Copyright (c) MASA Stack All rights reserved.
?

2023-03-23 12:24 UTC, zhenlei520 commented on src/BuildingBlocks/Isolation/Masa.BuildingBlocks.Isolation/IIsolationConfigProvider.cs
> +    TModuleConfig? GetModuleConfig<TModuleConfig>(string sectionName, string name = "") where TModuleConfig : class;
ComponentConfig？

2023-03-23 12:27 UTC, zhenlei520 commented on src/BuildingBlocks/Isolation/Masa.BuildingBlocks.Isolation/Options/IsolationOptions.cs
> +        MultiTenantType = typeof(Guid);
MultiTenantIdType

When the multi-tenant id type is not set, Guid is used by default

2023-03-27 05:08 UTC, doddgu requested changes

2023-03-27 05:08 UTC, doddgu commented on src/BuildingBlocks/Isolation/Masa.BuildingBlocks.Isolation/DefaultIsolationConfigProvider.cs
> +            ModuleType = typeof(TComponentConfig),
ModuleType?

2023-03-27 05:08 UTC, doddgu commented on src/BuildingBlocks/Isolation/Masa.BuildingBlocks.Isolation/DefaultIsolationConfigProvider.cs
> +        if (modules.Count >= 1)
modules?

2023-03-27 05:08 UTC, doddgu commented on src/BuildingBlocks/Isolation/Masa.BuildingBlocks.Isolation/DefaultIsolationConfigProvider.cs
> +        return moduleInfo;
moduleInfo?

2023-03-27 05:08 UTC, doddgu commented on src/BuildingBlocks/Isolation/Masa.BuildingBlocks.Isolation/Internal/ComponentConfigRelationInfo.cs
> +    public Type ModuleType { get; set; }
Module?

2023-03-27 06:14 UTC, doddgu approved these changes

2023-03-27 06:14 UTC, merged