feat(stack sdk)/stack sdk caller
masastack/MASA.Framework pull request #508
Opened 2023-03-20 06:24 UTC by MayueCif

2023-03-21 08:26 UTC, doddgu approved these changes

2023-03-21 13:08 UTC, zhenlei520 requested changes

2023-03-21 13:08 UTC, zhenlei520 commented on src/Contrib/Service/Caller/Authentication/Masa.Contrib.Service.Caller.Authentication.Standard/Extensions/MasaCallerClientBuilderExtensions.cs
> +        return UseAuthentication(masaCallerClientBuilder, (serviceProvider) => { return serviceProvider.GetRequiredService<TokenProvider>(); });
Infinite loop?

2023-03-22 03:40 UTC, zhenlei520 approved these changes
LGTM

2023-03-22 10:19 UTC, merged