feat:add default no tracking and default table name pularl for EfCore
masastack/MASA.Framework pull request #517
Opened 2023-03-24 12:20 UTC by MapleWithoutWords

2023-03-27 03:42 UTC, zhenlei520 requested changes

2023-03-27 03:42 UTC, zhenlei520 commented on src/Contrib/Data/Orm/EFCore/Masa.Contrib.Data.EFCore/Extensions/ServiceCollectionExtensions.cs
> +        bool enableSoftDelete, bool enablePluralizingTableName)
new line

2023-03-27 03:42 UTC, zhenlei520 commented on src/Contrib/Data/Orm/EFCore/Masa.Contrib.Data.EFCore/MasaDbContext.cs
> +        this.ChangeTracker.QueryTrackingBehavior = QueryTrackingBehavior.NoTracking;
Replace this or to base

2023-03-27 03:42 UTC, zhenlei520 commented on src/Contrib/Data/Orm/EFCore/Masa.Contrib.Data.EFCore/MasaDbContext.cs
> +        if (Options.EnablePluralizingTableName)
Turn on plurals?

2023-03-27 03:42 UTC, zhenlei520 commented on src/Contrib/StackSdks/Masa.Contrib.StackSdks.Tsc/Tracing/Handler/HttpClientInstrumentHandler.cs
> +        Console.WriteLine($"HttpClient's TraceId={activity?.TraceId}");
?

2023-03-27 06:45 UTC, doddgu approved these changes

2023-03-27 06:45 UTC, doddgu commented
@MapleWithoutWords Resole conflicts

2023-03-28 08:12 UTC, zhenlei520 approved these changes
LGTM @doddgu

2023-03-29 02:40 UTC, doddgu approved these changes

2023-03-29 02:40 UTC, merged