fix(tsc): fix record body bug in tracing
masastack/MASA.Framework pull request #538
Opened 2023-04-06 08:42 UTC by Qinyouzeng

- Read the body stream instead of synchronization.
 - if body size is less or equal 200k, tracing will record body ,else record in log with base64 encoding.

2023-04-06 15:12 UTC, zhenlei520 requested changes

2023-04-06 15:12 UTC, zhenlei520 commented on src/Contrib/StackSdks/Masa.Contrib.StackSdks.Tsc/Tracing/OpenTelemetryInstrumentationOptions.cs
> +    public void SetMaxBodySize(string val)
meaningless parameter name val

2023-04-06 15:12 UTC, zhenlei520 commented on src/Contrib/StackSdks/Masa.Contrib.StackSdks.Tsc/Tracing/ActivityExtensions.cs
> +            SetActivityBody(activity, streamTask.Result, GetHttpRequestMessageEncoding(httpRequest)).Wait();
Synchronous call to asynchronous? Use wait directly?

2023-04-06 15:12 UTC, zhenlei520 commented
[6 Code Smells](https://sonarcloud.io/project/issues?id=masastack_MASA.Framework&pullRequest=538&resolved=false&types=CODE_SMELL)

2023-04-07 02:13 UTC, zhenlei520 requested changes

2023-04-07 02:13 UTC, zhenlei520 commented on src/Contrib/StackSdks/Masa.Contrib.StackSdks.Tsc/Tracing/ActivityExtensions.cs
> +            OpenTelemetryInstrumentationOptions.Logger?.LogInformation("Request body in base64 encode:{Body}", body);
`Request body in base64 encode: {Body}`

2023-04-07 02:13 UTC, zhenlei520 commented on src/Contrib/StackSdks/Masa.Contrib.StackSdks.Tsc/Tracing/OpenTelemetryInstrumentationOptions.cs
> +    public static void SetMaxBodySize(string val)
meaningless parameter name val

2023-04-07 02:13 UTC, zhenlei520 commented on src/Contrib/StackSdks/Masa.Contrib.StackSdks.Tsc/Tracing/ActivityExtensions.cs
> +            OpenTelemetryInstrumentationOptions.Logger?.LogInformation("Request body in base64 encode:{Body}", body);
SetActivityBody(activity, httpRequest.Body, GetHttpRequestEncoding(httpRequest)).Wait();

Synchronous call to asynchronous? Use wait directly? on line19，line 34

2023-04-07 03:50 UTC, zhenlei520 approved these changes
LGTM @MayueCif

2023-04-07 11:43 UTC, MayueCif approved these changes
LGTM

2023-04-07 11:43 UTC, merged