fix: Cannot terminate sidecar when program exits abnormally
masastack/MASA.Framework pull request #598
Opened 2023-05-05 13:36 UTC by zhenlei520

# Description

Cannot terminate sidecar when program exits abnormally

## Issue reference

[issues-507](https://github.com/masastack/MASA.Framework/issues/507)

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Extended the documentation

2023-05-06 06:01 UTC, doddgu requested changes

2023-05-06 10:46 UTC, zhenlei520 commented on src/BuildingBlocks/Development/Masa.BuildingBlocks.Development.DaprStarter/Options/DaprOptions.cs
> +    private string _appIdDelimiter = DaprStarterConstant.DEFAULT_APPID_DELIMITER;
Processed

2023-05-06 10:46 UTC, zhenlei520 commented on src/BuildingBlocks/Development/Masa.BuildingBlocks.Development.DaprStarter/Options/DaprOptions.cs
> +                MasaArgumentException.ThrowIfLessThan(value.Value, -1, nameof(MaxConcurrency));
Processed

2023-05-06 10:46 UTC, zhenlei520 commented on src/BuildingBlocks/Development/Masa.BuildingBlocks.Development.DaprStarter/Options/DaprOptions.cs
> +    public override ushort? DaprGrpcPort
Processed

2023-05-06 10:46 UTC, zhenlei520 commented on src/BuildingBlocks/Development/Masa.BuildingBlocks.Development.DaprStarter/Options/DaprOptionsBase.cs
> +                MasaArgumentException.ThrowIfLessThanOrEqual(value.Value, (ushort)0, nameof(AppPort));
Processed

2023-05-08 02:12 UTC, doddgu approved these changes

2023-05-08 02:13 UTC, merged